FROM node:20-alpine

WORKDIR /app
COPY ./drylab-tools-frontend/package.json ./drylab-tools-frontend/package-lock.json ./
RUN npm ci

COPY ./drylab-tools-frontend/ .
RUN ls -la
ENV HOST=0.0.0.0
EXPOSE 3000

CMD ["sh", "-lc", "ls -la && npm run dev"]


